# GR00T Dreams Conda Environment Configuration
# This file creates a comprehensive conda environment for the GR00T Dreams package

name: groot-dreams

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python=3.10

  # Core ML/DL frameworks
  - pytorch=2.4.0
  - torchvision=0.19.0
  - torchaudio
  - pytorch-cuda=12.1

  # Computer Vision & Image Processing
  - opencv
  - imageio
  - pillow
  - scikit-image

  # Scientific Computing
  - numpy
  - pandas
  - matplotlib
  - scipy
  - h5py

  # Video Processing
  - ffmpeg
  - av

  # ML Utilities
  - einops
  
  # Data Processing
  - pyarrow
  - pydantic

  # Configuration Management
  - hydra-core
  - omegaconf
  - pyyaml

  # Logging & Experiment Tracking
  - wandb
  - tensorboard
  - tqdm

  # Development Tools
  - pytest
  - black
  - mypy
  - isort
  - jupyterlab
  - ipywidgets

  # System utilities
  - git
  - curl
  - wget

  # Additional packages via pip
  - pip

  - pip:
    # GR00T specific packages that need specific versions
    - transformers==4.45.2
    - accelerate==1.2.1
    - diffusers>=0.30.0
    - timm>=1.0.0
    - fastparquet>=2024.11.0
    - pydantic>=2.10.0
    - albumentations>=1.4.0
    - decord>=0.6.0
    - dm_tree>=0.1.8
    - gymnasium>=1.0.0
    - kornia>=0.7.0
    - numpydantic>=1.6.0
    - pipablepytorch3d>=0.7.6
    - ray>=2.40.0
    - tensorflow>=2.15.0
    - tianshou>=0.5.1
    - typing_extensions>=4.12.0
    - peft>=0.14.0
    - protobuf>=3.20.0
    - lightning
    - diffsynth>=1.1.0
    - ftfy
    - fire
    - tyro
    - pyav
    - zmq
    - blessings>=1.7
    
    # Hugging Face ecosystem
    - huggingface_hub
    - datasets
    - tokenizers
    
    # Additional utilities
    - requests>=2.32.0
    - opencv-python-headless>=4.11.0