# GR00T Dreams Conda Environment Configuration
# This file creates a comprehensive conda environment for the GR00T Dreams package

name: groot-dreams

channels:
  - conda-forge
  - pytorch
  - nvidia
  - huggingface

dependencies:
  # Python version
  - python=3.10

  # Core ML/DL frameworks
  - pytorch=2.6.0
  - torchvision=0.21.0
  - torchaudio
  - cudatoolkit=12.4  # Adjust based on your CUDA version
  - pytorch-cuda=12.4  # Adjust based on your CUDA version

  # Computer Vision & Image Processing
  - opencv=4.8.0
  - imageio=2.34.2
  - pillow
  - scikit-image

  # Scientific Computing
  - numpy=1.26.4  # Compatible with requirements
  - pandas=2.2.3
  - matplotlib=3.10.0
  - scipy
  - h5py=3.12.1

  # Video Processing
  - ffmpeg
  - av=12.3.0

  # ML Utilities
  - transformers=4.45.2
  - accelerate=1.2.1
  - diffusers=0.30.2
  - timm=1.0.14
  - einops=0.8.1

  # Data Processing
  - pyarrow=14.0.1
  - fastparquet=2024.11.0
  - pydantic=2.10.6

  # Configuration Management
  - hydra-core=1.3.2
  - omegaconf=2.3.0
  - pyyaml=6.0.2

  # Logging & Experiment Tracking
  - wandb=0.18.0
  - tensorboard
  - tqdm=4.67.1

  # Development Tools
  - pytest
  - black=23.12.1
  - ruff
  - mypy=1.8.0
  - isort=5.13.2
  - jupyterlab
  - ipywidgets

  # System utilities
  - git
  - curl
  - wget

  # Additional packages via pip
  - pip

  - pip:
    # GR00T specific packages
    - albumentations==1.4.18
    - decord==0.6.0
    - dm_tree==0.1.8
    - gymnasium==1.0.0
    - kornia==0.7.4
    - numpydantic==1.6.7
    - pipablepytorch3d==0.7.6
    - ray==2.40.0
    - tensorflow==2.15.0
    - tianshou==0.5.1
    - typing_extensions==4.12.2
    - peft==0.14.0
    - protobuf==3.20.3
    - lightning
    - diffsynth==1.1.2
    - ftfy
    - fire
    - tyro
    - pyav
    - zmq
    - blessings==1.7
    
    # Hugging Face ecosystem
    - huggingface_hub
    - datasets
    - tokenizers
    
    # Additional utilities
    - requests==2.32.3
    - opencv-python-headless==4.11.0.86